[[pages]]
path = "pages/home.py"
name = "Home"
icon = "🏠"

[[pages]]
path = "pages/demo.py"
name = "Modo Demo"
icon = ":books:"

[[pages]]
path = "pages/user_upload.py"
name = "Subir Telemetría"
icon = "📤"